apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cinemaabyss.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc }}