apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaWdjci5pbyI6IHsiYXV0aCI6ICJtbmVtY2hpbm92OmdocF8wcDdVczhBRDAzcXpCMFBWeGxFUEMzd2JkNGU2U0gyaWJXOTcifX0sImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsImN1cnJlbnRDb250ZXh0IjoiZGVza3RvcC1saW51eCJ9
type: kubernetes.io/dockerconfigjson