apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  # TODO: Generate your own dockerconfigjson
  # Run: cat ~/.docker/config.json | base64
  # Or generate using: echo -n "username:PAT_TOKEN" | base64
  .dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson